actor & node测试用例 Feat/node-test
SACLabs/DARC pull request #18
Opened 2024-05-09 07:49 UTC by sys555

1. actor在 pingpong场景下的对话用例；
2. node在 链、多入度、同一消息处理分发、条件分支下的测试用例；

2024-05-11 02:39 UTC, WangXuhongCN requested changes
PR要干净一点，把不需要的部分先删除，然后增加可读性，变量的命名清晰一些

2024-05-11 06:38 UTC, WanChengXue reviewed
没有测到重点上

2024-05-11 06:38 UTC, WanChengXue commented on tests/darc_test/node_test/test_chain.py
> +        return msgs
如果这个content是图片，压缩包，等，你怎么进行处理

2024-05-11 06:38 UTC, WanChengXue commented on tests/darc_test/test_node.py
> +#     # C.on_receive.assert_called_once_with(BtoD_msg)
注释了，则删掉

2024-05-11 06:38 UTC, WanChengXue commented on darc/darc/actor.py
> +        if message.to_agent in self.address_book and self.address_book[message.to_agent] in self.instance:
这个判断不对，如果message是广播类型，没有to_agent不就直接报错了

2024-05-11 06:38 UTC, WanChengXue commented on darc/darc/node.py
> +
注释代码删掉

2024-05-11 06:38 UTC, WanChengXue commented on tests/darc_test/node_test/test_chain.py
> +
你这段是想要表达什么意思？a.proxy().address_book的值是你在调用了start()之后自动赋予的吗？还是你这是mock写法？如果是mock写法为什么address_book中没有任何NodeType实例的地址吗？为什么a.proxy().instance会是这样的？

2024-05-11 06:38 UTC, WanChengXue commented on tests/darc_test/test_node.py
> +#     # C.on_receive.assert_called_once_with(BtoD_msg)
你这里的测试缺失，比如你上面那个定义了["A:C", "B:C"]这种消息类型，你这个Node中如何在只接收到了["A:C"], ["B:C"]类型的消息后，会自动的进行拼凑成这个联合类型的消息

2024-05-11 06:38 UTC, WanChengXue commented on tests/darc_test/node_test/test_multi_despatch.py
> +        )
你的test_chain, test_condition, test_gather冗余，只要有一个就够了，都是测message发出，然后另外一个actor能够将message正常接收到

2024-05-11 06:38 UTC, WanChengXue commented on tests/darc_test/test_actor.py
> +
这个actor类又是用来干什么的？你直接把register_actor函数放在abstract_actor类中不就好了

2024-05-11 06:38 UTC, WanChengXue commented on tests/darc_test/test_node.py
> +#     # C.on_receive.assert_called_once_with(BtoD_msg)
你要测试，如果我用装饰器增加了某个消息，那么Node中用什么来存放这个消息和回调？是{"A:B": callback}类型吗？

2024-05-11 06:44 UTC, sys555 commented on tests/darc_test/node_test/test_chain.py
> +        return msgs
再定一个dcontent类型

2024-05-11 06:47 UTC, sys555 commented on tests/darc_test/test_node.py
> +#     # C.on_receive.assert_called_once_with(BtoD_msg)
1. “你这个Node中如何在只接收到了["A:C"], ["B:C"]类型的消息后，会自动的进行拼凑成这个联合类型的消息”，只要看 D 中有没有收到C的消息就好了，场景定义有；
2. 是的，是{"A:B": callback}类型；

2024-05-11 06:49 UTC, sys555 commented on darc/darc/actor.py
> +        if message.to_agent in self.address_book and self.address_book[message.to_agent] in self.instance:
广播这个pr还没有测

2024-05-11 06:50 UTC, sys555 commented on darc/darc/node.py
> +
- 新commit删了
-

2024-05-11 06:50 UTC, sys555 commented on tests/darc_test/test_node.py
> +#     # C.on_receive.assert_called_once_with(BtoD_msg)
新commit删了

2024-05-11 06:51 UTC, sys555 commented on tests/darc_test/node_test/test_chain.py
> +
不是，这是mock写法，address_book 是 name : addr

2024-05-11 06:52 UTC, WanChengXue commented on tests/darc_test/node_test/test_chain.py
> +        return msgs
所以你需要提供一个content对象，能够支持文本，图片，压缩包等数据，而不要直接将文字放入进来

2024-05-11 06:52 UTC, sys555 commented on tests/darc_test/node_test/test_multi_despatch.py
> +        )
condition是冗余的，gather必须，因为有场景是需要多个message才触发process

2024-05-11 06:53 UTC, sys555 commented on tests/darc_test/test_actor.py
> +
这是outdated 的commit，最新的删除了register_actor

2024-05-11 06:56 UTC, WanChengXue commented on darc/darc/actor.py
> +        if message.to_agent in self.address_book and self.address_book[message.to_agent] in self.instance:
那你这个写死在这里，兼容广播就要开一个新的函数了，为啥不兼容

2024-05-11 06:57 UTC, WanChengXue commented on tests/darc_test/test_node.py
> +#     # C.on_receive.assert_called_once_with(BtoD_msg)
> 1. “你这个Node中如何在只接收到了["A:C"], ["B:C"]类型的消息后，会自动的进行拼凑成这个联合类型的消息”，只要看 D 中有没有收到C的消息就好了，场景定义有；
> 2. 是的，是{"A:B": callback}类型；

怎么自动合并？是不是需要在Node这个节点中实现？那么实现的过程中对应的函数的测试需要有

2024-05-11 06:58 UTC, WanChengXue commented on tests/darc_test/node_test/test_chain.py
> +
b节点是所谓的Gate类型节点吗？

2024-05-11 06:59 UTC, sys555 commented on tests/darc_test/test_node.py
> +    msg = Message(message_name = "PingMessage", from_agent = "pingNode", to_agent = "pongNode", content = "empty")
ok

2024-05-11 06:59 UTC, WanChengXue commented on tests/darc_test/node_test/test_multi_despatch.py
> +        )
但是你的测试代码和chain代码有什么区别吗？

2024-05-13 08:51 UTC, WangXuhongCN approved these changes
LGTM

2024-05-13 09:01 UTC, merged