Feat/backup
SACLabs/DARC pull request #35
Opened 2024-06-06 10:29 UTC by sys555

### Summary :memo:
_Write an overview about it._

### Details
_Describe more what you did on changes._
1. (...)
2. (...)

### Bugfixes :bug: (delete if dind't have any)
-

### Checks
- [ ] Closed #798
- [ ] Tested Changes
- [ ] Stakeholder Approval

2024-06-17 10:37 UTC, WanChengXue requested changes

2024-06-17 10:37 UTC, WanChengXue commented on darc/controller.py
>          # 检查config["node"]中提到的所有类，为未实例化的类创建默认实例
为什么要为没有实例化真实节点的类设置默认实例？需求在哪里？如果一定要有默认实例，为什么不先给每一个类型的节点设置一个默认实例，然后再根据参数构造真正的实例节点。69-76行放到86行下。

你这个init函数中一次性做了三个工作，完全可以拆开成三个函数，并且后续增加对每一个函数的测试

2024-06-17 10:37 UTC, WanChengXue commented on darc/controller.py
> +            self._router_dict[router_name] = router_instance
这个起名特别misleading，改成_spawn_new_router会容易理解许多

2024-06-17 10:37 UTC, WanChengXue commented on darc/controller.py
> +                    .spawn_real_instance(cls, args)
这个spawn_real_instance改成spawn_nodegate应该会容易理解一些

你这种写法默认是单例写法，对于外人来说很难理解这段代码的含义。此处需要解释一下，对其余的router来讲，如果名字中含有了给定的nodegate_type，应该如何处理？

2024-06-17 10:37 UTC, WanChengXue commented on tests/node_test/test_chain.py
> +#         # assert c.message_in_inbox(b_to_c_msg).get() is True
如果全部注释，可要考虑删除掉这个文件，或者下一个pr再提交这个文件

2024-06-17 10:37 UTC, WanChengXue commented on darc/controller.py
> +                )
找所有类型所有实例节点，为啥不直接找到对应的nodegate实例，从这个nodegate实例中拿出所有的node实例

2024-06-17 10:37 UTC, WanChengXue commented on darc/controller.py
> +                )
你的129行开始和118行下面重复，封装一个函数就好了

2024-06-17 10:37 UTC, WanChengXue commented on darc/controller.py
> +
可以考虑先添加边，再实例化具体的节点

2024-06-17 10:37 UTC, WanChengXue commented on darc/controller.py
> +
叫做属性奇怪，容易误导。这个地方应该是用来实例化节点的参数，函数node_args会好很多

2024-06-17 10:37 UTC, WanChengXue commented on darc/controller.py
> +        node_class = eval(node)  # 通过名字恢复类对象,注意这里的安全风险
eval函数尽量别用

2024-06-17 13:52 UTC, WanChengXue requested changes

2024-06-17 13:52 UTC, WanChengXue commented on darc/llm/proxy/query.py
> +    # return "Please answer the question using about 2 - 8 words"
你这个函数需要给出对应的返回类型，return一个字符串会很误解

2024-06-17 13:52 UTC, WanChengXue commented on darc/llm/proxy/query.py
> +    user_message = question + gen_num_words()
user_message很奇怪，为什么question还要加一个空字符串？

2024-06-17 13:52 UTC, WanChengXue commented on darc/llm/proxy/query.py
> +    response_list = [get_response_sync(question), get_response_sync(question)]
这个是什么意思，为什么要对一个问题进行两次llm的调用？如果你说是对agent的调用，那么llm应该放在agent内部

2024-06-17 13:52 UTC, WanChengXue commented on darc/llm/proxy/query.py
> +    return [
同上问题？这个函数的意义在哪里？应用场景

2024-06-17 13:52 UTC, WanChengXue commented on darc/llm/proxy/query.py
> +    return response["choices"][0]["message"]["content"]
你在35行已经获取到的就是content，你再调用一次显然会报错。其外，为什么多个选项你永远只给第一个？

2024-06-17 13:52 UTC, WanChengXue commented on darc/llm/proxy/query.py
> +            Please wrap the amount of gold you are willing to pay with ()."
手写prompt永远是最下策，比如现在的clickprompt包或者其他的包可以解决你的问题

2024-06-17 13:52 UTC, WanChengXue commented on darc/llm/proxy/query.py
> +    LLMSafetyChallenge/darc/llm/proxy/snake.py"
不管什么时候绝对路径都不应该包含在代码里面

2024-06-17 13:52 UTC, WanChengXue commented on darc/llm/proxy/query.py
> +
整个文件看上去和actor model没有任何的联系，仅仅是对llm的一次调用而已，放在这里是否有必要？

2024-06-17 13:52 UTC, WanChengXue commented on darc/message.py
handle_name字段是用来干啥的

2024-06-17 13:52 UTC, WanChengXue commented on darc/mock/mock_llm_query.py
> +```"""
这个mock文件夹就很奇怪，可以直接删掉

2024-06-17 14:21 UTC, WanChengXue requested changes

2024-06-17 14:21 UTC, WanChengXue commented on darc/node_gate.py
在我的设计中，node_gate_link_type是类似PingPonger--PingPonger的类型与类型的链接字符串，它代表的是一个路由，对应唯一的路由地址，你改成了列表本质上说不通了，不会存在一个类型链接出现多个路由地址，并且你的43-45行要缩进

2024-06-17 14:21 UTC, WanChengXue commented on darc/node_gate.py
> +            # 要么修改 from_node_type_name 要么 修改 from_node_type_name变更逻辑
你不要动router和nodegate的代码，直接从gmaf库原封不动移动过来就好，在gmaf库中所有的测试都是通过的，你这在consumer中收到from_node_type_name="Consumer"的bug不来源于nodegate

2024-06-17 14:21 UTC, WanChengXue commented on darc/node_gate.py
> +                    ]
为什么要修改一个combined_list出来？如果消息来源于Router，并且当前处于NodeGate位置，则只需要将message发送给当前NodeGate下面所有控制的实例就好了。NodeGate的instance中除了所有的Node实例也就只剩router实例，你排除掉所有的router不就好了

2024-06-17 14:21 UTC, WanChengXue commented on darc/node_gate.py
> +                )
如果数据是从RealNode过来，那么NodeGate需要转发到对应的Router上面，由于message.message_name就是对应NodeType--NodeType，你干啥还要搞一个[0]出来

2024-06-17 14:21 UTC, WanChengXue commented on darc/node_gate.py
> +        # 会导致多个 new actor 的 node id 一样, 导致生成失败
这个失败是因为你所有类型的Node都采用一套id，回去改动Node类，或者实在不行你就把我的gmaf中的Node抄过来

2024-06-17 14:21 UTC, WanChengXue commented on tests/test_async.py
> +#         # d 邮箱中有 CtoD_msg, 证明 b 收到了 AtoC_msg、BtoC_msg 并进行处理
没用就删掉，下一个版本提交

2024-06-17 14:23 UTC, WanChengXue requested changes
所有的错误来源于对gmaf库的移植，你基本不用动router和nodegate，只需要对node类进行少量的改动即可

2024-06-18 02:03 UTC, sys555 commented on darc/controller.py
能用了，下个pr提交

2024-06-18 02:05 UTC, allenwoods requested changes

2024-06-18 02:05 UTC, allenwoods commented on darc/llm/.DS_Store
删去，.gitignore里面加上mcos的配置

2024-06-18 10:45 UTC, closed without merging